### PR TITLE
Fix editUrl

### PR DESCRIPTION
**Pull request by LinkossLink**
This fixes issue #40

### CODE REVIEW

**Review by xaviervia — APPROVED** [review]
Good find, thanks!

**Comment by LinkossLink** [comment]
> Hi @LinkossLink , so you know, it seems we have some issues on our side with the CI pipeline which is currently failing for PRs coming from forks. That's why we haven't merged yet 👍 

Got it

**Comment by xaviervia** [comment]
@LinkossLink we have fixed the issue on our `documentation` branch, if you do a `Fetch upstream` on your fork, it should work now :) 

Screenshot 2022-06-29 at 16 43 56

**Comment by xaviervia** [comment]
Merged! Thanks again @LinkossLink

**Pull request merged**
