### PR TITLE
Documentation improvements

### PR DESCRIPTION
**Pull request by AdamRamberg**
Found some stuff when reading through the docs that I believe we should fix / clarify. Think most of it is pretty straight forward. However, I would like to get input on my changes regarding `remoteSelector`. From my understanding the `remoteSelector` is actually returning a new facet and not a selector. I changed the docs to clarify that, but as I said, I would like to get some feedback on that.

### CODE REVIEW

**Review by jacobbergdahl — CHANGES_REQUESTED** [review]
Nice updates, Adam! I'm not sure about changing the naming convention of selectors, however. I think `remote.md` might need to be reverted, but Paulo and Fernando are certainly more qualified than me at making that call.

**Comment by AdamRamberg** [comment]
> Nice updates, Adam! I'm not sure about changing the naming convention of selectors, however. I think `remote.md` might need to be reverted, but Paulo and Fernando are certainly more qualified than me at making that call.

Regarding the name change of selectors. A call to `remoteSelector` actually returns a `RemoteFacet<V>` and not a selector, a selector is instead passed in to the `remoteSelector` function as the first argument. While reading the documentation I thought that naming the return value from calling `remoteSelector` a "selector" was confusing and hence the change. 

Example:
```tsx
const userNameSelector = remoteSelector(({ user }) => user.name, [profileFacet])
```
`({ user }) => user.name` is the selector and `userNameSelector` is a `RemoteFacet`. 

Just realised that the order of the parameters in the example in the documentation is incorrect. Will change that in a new commit.

**Comment by xaviervia** [comment]
I agree, the result of the `remoteSelector` call is a `RemoteFacet`, not a selector. I think the change to `userNameFacet` is good. 

On top of that, we have discussed in the past to rename `RemoteFacet` to `SharedFacet`, since it better reflects what it does (memory that is shared with the backend, rather than _remote_, which might imply a network connection). What do you think? I can do that in a separate PR

**Comment by AdamRamberg** [comment]
> On top of that, we have discussed in the past to rename `RemoteFacet` to `SharedFacet`, since it better reflects what it does (memory that is shared with the backend, rather than _remote_, which might imply a network connection). What do you think? I can do that in a separate PR

I think that `SharedFacet` is a slightly better name than `RemoteFacet`, since like you say _remote_ implies that there might be a network request. However, if we ought to do the change, then we should also change the name _remote_ everywhere, which means renaming `remoteSelector` to `sharedSelector`, `RemoteFacetDriverProvider` to `SharedFacetDriverProvider`, etc. It's a pretty large change, so I understand if it might not be worth it though. I'm ok with either (keep it or change it).

**Comment by AdamRamberg** [comment]
Pushed a new commit where I adjusted the documentation in `remote.md` so example function calls receives correct parameters. It seems like `initialValue` for both `remoteSelector` and `remoteDynamicSelector` has been removed. Is that something we want back? (could be added in a new PR if we want it back)

**Comment by xaviervia** [comment]
If we had removed the `initialValue`, we probably don't need it. Thanks for updating the docs on that.

**Review by jacobbergdahl — APPROVED** [review]
I had a brief dialogue with Adam regarding changing the naming for the result of `remoteSelector`, and I am on board with the change 😄 Looks great! 👍

**Pull request merged**
